/*
 * webapi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/mattiasasplund/gotest/go"
)

func main() {
	log.Printf("Server started")

	WeatherForecastApiService := openapi.NewWeatherForecastApiService()
	WeatherForecastApiController := openapi.NewWeatherForecastApiController(WeatherForecastApiService)

	router := openapi.NewRouter(WeatherForecastApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
