/*
 * webapi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type WeatherForecast struct {

	Date time.Time `json:"date,omitempty"`

	TemperatureC int32 `json:"temperatureC,omitempty"`

	TemperatureF int32 `json:"temperatureF,omitempty"`

	Summary *string `json:"summary,omitempty"`
}

// AssertWeatherForecastRequired checks if the required fields are not zero-ed
func AssertWeatherForecastRequired(obj WeatherForecast) error {
	return nil
}

// AssertRecurseWeatherForecastRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of WeatherForecast (e.g. [][]WeatherForecast), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseWeatherForecastRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aWeatherForecast, ok := obj.(WeatherForecast)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertWeatherForecastRequired(aWeatherForecast)
	})
}
